name: tfsec
on: push

jobs:
  tfsec:
    uses: skyleague/node-standards/.github/workflows/reusable-tfsec.yml@main
    with:
      terraform-version: "1.3.0"
      working-directory: "./"
      tfsec-var-files: '["test/default.tfvars"]'
